import { getCurriculumWeeks, getCurriculumAreas } from '@/lib/actions/curriculum';
import CurriculumClient from './client-page';

const FALLBACK_PRENEUR_AREAS = [
  {
    num: '01',
    title: '조직 운영 & 스케일업',
    subtitle: 'Operations & Scale-up',
    description:
      'SPEC을 하나의 스타트업으로 정의하고 시스템 설계를 주도합니다. 운영 체계화와 문화 구축을 통해 조직의 선행 성장을 최우선으로 실현합니다.',
    activities: [
      'SPEC 내부 운영 프로세스 설계 및 최적화',
      '기수별 온보딩/오프보딩 체계 구축',
      '조직 문화 정의 — 행동 강령, 의사결정 구조 수립',
      'OKR 기반 분기별 목표 설정 및 트래킹',
      '운영 매뉴얼 작성 — 후속 기수를 위한 레거시 구축',
    ],
  },
  {
    num: '02',
    title: '투자사 IR & 파트너십',
    subtitle: 'Investor Relations & Partnerships',
    description:
      '전략적 IR과 파트너십 발굴로 핵심 자원을 확보합니다. 자원 유입을 체계화하여 SPEC이 지속 성장하는 비즈니스 구조를 설계합니다.',
    activities: [
      '투자사/기업 대상 SPEC IR 덱 작성 및 피칭',
      '전략적 파트너십 발굴 — 기업, 대학, 정부 기관',
      '후원 유치 전략 수립 및 실행',
      '외부 협업 프로그램 기획 (해커톤, 공동 세션 등)',
      'SPEC 브랜드 가치 제안 정리 및 커뮤니케이션',
    ],
  },
  {
    num: '03',
    title: 'Learner 서포트 & 멘토링',
    subtitle: 'Learner Support & Mentoring',
    description:
      '밀착 코칭으로 러너의 잠재력을 깨우고 성장을 견인합니다. 지표를 정교하게 트래킹하여 러너와 SPEC의 공동 성공을 실현합니다.',
    activities: [
      'Learner 팀 주간 코칭 세션 운영',
      '오피스아워 — 1:1 멘토링 및 문제 해결',
      'Learner 성장 지표 대시보드 관리 및 분석',
      '외부 멘토 네트워크 연결 — 현직 창업가, VC, 전문가',
      '데모데이 준비 서포트 — 피치 리허설, 자료 검토',
    ],
  },
  {
    num: '04',
    title: '커뮤니티 빌딩',
    subtitle: 'Community Building',
    description:
      '알럼나이 네트워크와 외부 행사를 기획하여 SPEC의 영향력을 넓힙니다. 차별화된 브랜드 빌딩으로 창업 생태계에 SPEC의 존재감을 각인시킵니다.',
    activities: [
      '알럼나이 네트워크 활성화 — 월간 동문 모임, 뉴스레터',
      '외부 행사 기획 및 운영 — 밋업, 네트워킹 이벤트',
      'SPEC 브랜드 관리 — SNS, 콘텐츠 전략',
      '타 창업 커뮤니티와의 교류 및 협업',
      '차기 기수 리쿠르팅 전략 수립 및 실행',
    ],
  },
];

const FALLBACK_LEARNER_WEEKS = [
  {
    week: 1,
    topic: 'SPEC 철학 / SPEC 소개 / 프러너 4기 발표 / 전원 Edge(자기소개) 발표 / 아이스브레이킹',
    objectives: '프로그램 시작',
    assignment: '0원',
    notes: '테토 에겐 테스트',
    start_date: '2026-03-27',
    end_date: null,
  },
  {
    week: 2,
    topic: '제로투원 챌린지 소개 / 돈 버는 100가지 방법 / 팀별 브레인스토밍 / 아이디어 발표',
    objectives: '',
    assignment: '매출 자유 (팀)\n자본금 10만원',
    notes: '장애물 피하기 아케이드 게임',
    start_date: '2026-04-03',
    end_date: null,
  },
  {
    week: 3,
    topic: '제로투원 챌린지 (끝) / 비즈니스 케이스 스터디',
    objectives: '',
    assignment: '매출 자유 (팀)\n자본금 10만원',
    notes: '음성인식 아케이드 게임',
    start_date: '2026-04-10',
    end_date: null,
  },
  {
    week: 'OFF',
    topic: '시험 기간',
    objectives: '',
    assignment: '-',
    notes: '',
    start_date: '2026-04-13',
    end_date: '2026-04-24',
  },
  {
    week: 4,
    topic: '10만원 챌린지 / 팀별 아이디어 발표 / 프리토타입 검증 방법 / 제로투원 챌린지 (성과 공유)',
    objectives: '',
    assignment: '매출 10만원 (팀)\n자본금 10만원',
    notes: '식단관리 서비스',
    start_date: '2026-05-01',
    end_date: null,
  },
  {
    week: 5,
    topic: '10만원 챌린지 / 데이터 분석 교육',
    objectives: '',
    assignment: '매출 10만원 (팀)\n자본금 10만원',
    notes: 'AI 연봉 예측 서비스',
    start_date: '2026-05-08',
    end_date: null,
  },
  {
    week: 6,
    topic: '10만원 챌린지 성과 공유 / 30만원 챌린지 / 아이디어 발표',
    objectives: '',
    assignment: '매출 10만원 (팀)\n자본금 10만원\n\n매출 30만원 (팀)\n자본금 10만원',
    notes: 'AI 꿈 해몽 서비스',
    start_date: '2026-05-15',
    end_date: null,
  },
  {
    week: 7,
    topic: '30만원 챌린지 / 비즈니스 설계',
    objectives: '',
    assignment: '-',
    notes: '블로그 이웃, 댓글 자동 보내기 서비스',
    start_date: '2026-05-22',
    end_date: null,
  },
  {
    week: 8,
    topic: '30만원 챌린지 성과 공유 / 가설 수립 / 인터뷰 / 검증 실험 설계',
    objectives: '',
    assignment: '-',
    notes: '유튜브 요약 서비스',
    start_date: '2026-05-29',
    end_date: null,
  },
  {
    week: 9,
    topic: '검증 실험 현황 공유',
    objectives: '',
    assignment: '-',
    notes: '실시간 주식/코인 자동 분석 리포터',
    start_date: '2026-06-04',
    end_date: null,
  },
  {
    week: 10,
    topic: 'IR 특강 / 검증 실험 결과 공유',
    objectives: 'BOOTCAMP 졸업',
    assignment: '-',
    notes: '나만의 로컬 파일 전문 비서',
    start_date: '2026-06-05',
    end_date: null,
  },
  {
    week: 'EVENT',
    topic: '1박2일 / 아이디어 피칭 + 팀 스피드 데이팅 + 팀 확정 + 48시간 프로젝트',
    objectives: '팀 확정',
    assignment: '-',
    notes: '',
    start_date: '2026-06-06',
    end_date: '2026-06-07',
  },
  {
    week: 'OFF',
    topic: '시험 기간 - MVP 해커톤으로 복귀',
    objectives: '',
    assignment: '-',
    notes: '',
    start_date: '2026-06-08',
    end_date: '2026-06-19',
  },
  {
    week: 11,
    topic: 'MVP 정의 / 스프린트 방법론 / DB 설계 기초 / 기능 명세서 / WBS / IA / 화면 설계서 / Jira / Figjam',
    objectives: 'MVP 해커톤',
    assignment: '-',
    notes: '',
    start_date: '2026-06-20',
    end_date: null,
  },
  {
    week: 'EVENT',
    topic: 'MVP 완성 스프린트 (1박2일) / 바이브 코딩 교육',
    objectives: 'MVP 해커톤',
    assignment: '-',
    notes: '',
    start_date: '2026-06-27',
    end_date: '2026-06-28',
  },
  {
    week: 12,
    topic: '빠른 이터레이션 / API 연동 / 유저 피드백 수집',
    objectives: '',
    assignment: '',
    notes: '',
    start_date: '2026-07-03',
    end_date: null,
  },
  {
    week: 13,
    topic: '런칭의 기술 (온/오프라인/하이브리드) / 배포 및 모니터링',
    objectives: '',
    assignment: '만원',
    notes: '',
    start_date: '2026-07-10',
    end_date: null,
  },
  {
    week: 14,
    topic: '그로스 해킹 / 유닛 이코노믹스 / 획득 비용 (CAC) / 생애 가치 (LTV) / AARRR 퍼널 분석',
    objectives: '연합 활동',
    assignment: '만원',
    notes: '',
    start_date: '2026-07-17',
    end_date: null,
  },
  {
    week: 15,
    topic: '데이터 기반 의사결정 / 리텐션 차트 분석 / 이탈 지점 파악 / 코호트 분석 기법',
    objectives: '',
    assignment: '만원',
    notes: '',
    start_date: '2026-07-24',
    end_date: null,
  },
  {
    week: 16,
    topic: '피보팅 기술 / 가설 실패를 인정하는 법 / 핵심 가치만 남기고 깎아내기',
    objectives: '',
    assignment: '만원',
    notes: '',
    start_date: '2026-08-28',
    end_date: null,
  },
  {
    week: 'EVENT',
    topic: '중간 데모데이 전야제 / 피칭 리허설 / 외부 심사위원 피칭',
    objectives: '중간 데모데이 &\n서울대 창업동아리와 합동 데모데이',
    assignment: '-',
    notes: '',
    start_date: '2026-08-29',
    end_date: '2026-08-30',
  },
  {
    week: 17,
    topic: '유로 마케팅 / 콘텐츠 전략 / Meta/Google 광고 기초 / 고효율 소재 제작 / AB 테스트',
    objectives: 'Demo Eve 밤샘 (8/13)',
    assignment: '3만원',
    notes: '',
    start_date: '2026-09-04',
    end_date: null,
  },
  {
    week: 18,
    topic: '바이럴 루프 / 커뮤니티 빌딩 / 유저가 유저를 불러오는 장치 설계 / 초기 팬덤 형성 전략',
    objectives: '',
    assignment: '3만원',
    notes: '',
    start_date: '2026-09-11',
    end_date: null,
  },
  {
    week: 19,
    topic: '운영 자동화 / No-Code 확장 / 반복적인 CS / 운영 업무 자동화(Zapier, Make 활용)',
    objectives: '',
    assignment: '3만원',
    notes: '',
    start_date: '2026-09-18',
    end_date: null,
  },
  {
    week: 20,
    topic: '지표가 안 나오는 이유 처절하게 분석하기 (Self-Roasting)',
    objectives: '연합 활동',
    assignment: '3만원',
    notes: '',
    start_date: '2026-09-25',
    end_date: null,
  },
  {
    week: 21,
    topic: '스케일링이란? / 병목 지점 찾기 / 자동화 심화',
    objectives: '',
    assignment: '10만원',
    notes: '',
    start_date: '2026-10-02',
    end_date: null,
  },
  {
    week: 22,
    topic: '구독 서비스 vs 건당 결제 / 가격 심리학과 수익 극대화 / 수익모델 구체화',
    objectives: '',
    assignment: '10만원',
    notes: '',
    start_date: '2026-10-09',
    end_date: null,
  },
  {
    week: 'OFF',
    topic: '시험 기간 - IR 준비 계속 / VC 콜드메일 권장',
    objectives: '',
    assignment: '-',
    notes: '',
    start_date: '2026-10-12',
    end_date: '2026-10-23',
  },
  {
    week: 23,
    topic: '고객 경험(CX) / 브랜드 보이스 /고객 경험(CX) / 브랜드 보이스',
    objectives: '연합 활동',
    assignment: '10만원',
    notes: '',
    start_date: '2026-10-30',
    end_date: null,
  },
  {
    week: 24,
    topic: '법인 설립 / 주주간 계약서 /저작권/ 개인정보보호법',
    objectives: '',
    assignment: '10만원',
    notes: '',
    start_date: '2026-11-06',
    end_date: null,
  },
  {
    week: 'EVENT',
    topic: '최종 데모데이 준비 (1박2일) / 피칭 리허설',
    objectives: 'Final 데모데이 (11/14-15)',
    assignment: '-',
    notes: '',
    start_date: '2026-11-14',
    end_date: '2026-11-15',
  },
  {
    week: 25,
    topic: 'Sean Ellis 테스트 / 재구매율, 재방문율 기반 PMF 판단',
    objectives: '연합 활동',
    assignment: '30만원',
    notes: '',
    start_date: '2026-11-20',
    end_date: null,
  },
  {
    week: 26,
    topic: '초기 팀 빌딩 전략 / 컬처 핏(Culture Fit) 정의 / 면점',
    objectives: '',
    assignment: '30만원',
    notes: '',
    start_date: '2026-11-27',
    end_date: null,
  },
  {
    week: 27,
    topic: '5분 피칭 / 3분 Q&A 대응 전략 / 시각 자료 시인성 개선',
    objectives: 'Final 데모데이 (11/7-8)',
    assignment: '30만원',
    notes: '',
    start_date: '2026-12-04',
    end_date: null,
  },
  {
    week: 28,
    topic: '최종 리허설 / Q&A 마지막 준비 / 데모데이 당일 흐름',
    objectives: '',
    assignment: '100만원',
    notes: '',
    start_date: '2026-12-11',
    end_date: null,
  },
  {
    week: 29,
    topic: 'SPEC 4기 전체 회고 / 다음 단계 안내 / 알럼나이 네트워크',
    objectives: '',
    assignment: '100만원',
    notes: '',
    start_date: '2026-12-18',
    end_date: null,
  },
  {
    week: 30,
    topic: '스타트업 다음 단계 / 알럼나이 혜택 / 수료식',
    objectives: '프로그램 종료',
    assignment: '지속',
    notes: '',
    start_date: '2026-12-25',
    end_date: null,
  },
];

export default async function CurriculumPage() {
  const [weeksResult, areasResult] = await Promise.all([
    getCurriculumWeeks('learner'),
    getCurriculumAreas('preneur'),
  ]);

  const dbWeeks = weeksResult.data ?? [];
  const dbAreas = areasResult.data ?? [];
  const hasDbCurriculum = dbWeeks.length > 0 || dbAreas.length > 0;

  const displayWeeks = hasDbCurriculum ? dbWeeks : FALLBACK_LEARNER_WEEKS;
  const displayAreas = hasDbCurriculum ? dbAreas : FALLBACK_PRENEUR_AREAS;

  return <CurriculumClient initialWeeks={displayWeeks} initialAreas={displayAreas} />;
}
