-- 035-seed-learner-curriculum.sql
-- Seed learner track curriculum weeks from hardcoded client data
-- Source: app/curriculum/client-page.tsx → learnerWeeks[] (37 entries)

BEGIN;

DELETE FROM public.curriculum_weeks
 WHERE track = 'learner' AND batch = 'default';

INSERT INTO public.curriculum_weeks
  (track, week_number, week_label, topic, objectives, assignment, notes, batch, sort_order)
VALUES
  ('learner', 1,    'Week 1',  'Kickoff',                                                      'SPEC 철학 / 전원 Edge(자기소개) 발표 / 러너 3기 발표 / 아이스브레이킹',                                           '0원',                              '프로그램 시작',                                          'default', 1),
  ('learner', 2,    'Week 2',  '제로투원 챌린지',                                                 '제로투원 챌린지 소개 / 돈 버는 100가지 방법 / 팀 배정 / 슬랙, 노션 교육 / 팀별 브레인스토밍 / 아이디어 발표',         '매출 자유·자본금 10만원',             NULL,                                                     'default', 2),
  ('learner', 3,    'Week 3',  '제로투원 챌린지 (성과 공유) / 비즈니스 케이스 스터디',                  '제로투원 챌린지 성과 공유 / 프리토타입 / 비즈니스 케이스 스터디 / 창업 이론 학습 / 사업 전략 수립',                    '매출 자유·자본금 10만원',             NULL,                                                     'default', 3),
  ('learner', NULL, 'OFF',     '1학기 중간고사 OFF',                                              '시험 기간',                                                                                                   '-',                                NULL,                                                     'default', 4),
  ('learner', 4,    'Week 4',  '10만원 챌린지',                                                   '10만원 챌린지 / 팀 배정 / 아이디어 발표 / 프리토타입 검증 방법 / 피그마 간단 실습',                                  '매출 10만원·자본금 10만원',           NULL,                                                     'default', 5),
  ('learner', 5,    'Week 5',  '10만원 챌린지 (중간) / 데이터 분석 교육',                             '10만원 챌린지 / 데이터 분석 교육',                                                                              '매출 10만원·자본금 10만원',           NULL,                                                     'default', 6),
  ('learner', 6,    'Week 6',  '10만원 챌린지 (성과 공유) / 30만원 챌린지',                           '10만원 챌린지 성과 공유 / 30만원 챌린지 / 아이디어 발표',                                                         E'매출 10만원·자본금 10만원\n매출 30만원·자본금 10만원', NULL,                                    'default', 7),
  ('learner', 7,    'Week 7',  '30만원 챌린지 (중간) / 비즈니스 설계',                               '30만원 챌린지 / 비즈니스 이해 / 기회 발굴 / 비즈니스 모델 설계',                                                   '-',                                NULL,                                                     'default', 8),
  ('learner', 8,    'Week 8',  '30만원 챌린지 (성과 공유) / 인터뷰, 가설 검증 설계',                   '30만원 챌린지 성과 공유 / 가설 수립 / 인터뷰 / 검증 실험 설계',                                                    '-',                                NULL,                                                     'default', 9),
  ('learner', 9,    'Week 9',  '인터뷰 결과 공유',                                                 '인터뷰 결과 공유',                                                                                             '-',                                NULL,                                                     'default', 10),
  ('learner', 10,   'Week 10', 'BOOTCAMP 졸업 & IR 특강',                                         'BOOTCAMP 졸업 / STARTUP 페이즈 소개 / 아이디어톤 안내 / IR 특강',                                                '-',                                'BOOTCAMP 졸업',                                          'default', 11),
  ('learner', NULL, 'EVENT',   '아이디어톤',                                                       '1박2일 / 아이디어 피칭 + 팀 스피드 데이팅 + 팀 확정 + 48시간 프로젝트',                                            '-',                                '팀 확정',                                                'default', 12),
  ('learner', NULL, 'OFF',     '1학기 기말고사 OFF',                                              '시험 기간',                                                                                                   '-',                                NULL,                                                     'default', 13),
  ('learner', 11,   'Week 11', 'MVP 빌드 전 구체화',                                              'MVP 정의 / 스프린트 방법론 / DB 설계 기초 / 기능 명세서 / WBS / IA / 화면 설계서 / Jira / Figjam',                 '-',                                'MVP 해커톤',                                             'default', 14),
  ('learner', NULL, 'EVENT',   'MVP 해커톤',                                                      'MVP 완성 스프린트 (1박2일) / 바이브 코딩 교육',                                                                  '-',                                'MVP 해커톤',                                             'default', 15),
  ('learner', 12,   'Week 12', 'MVP 개발 스프린트',                                               '빠른 이터레이션 / API 연동 / 유저 피드백 수집',                                                                   '-',                                NULL,                                                     'default', 16),
  ('learner', 13,   'Week 13', '런칭',                                                            '런칭의 기술 (온/오프라인/하이브리드) / 배포 및 모니터링',                                                           '만원',                              NULL,                                                     'default', 17),
  ('learner', 14,   'Week 14', '그로스 해킹과 유닛 이코노믹스',                                     '그로스 해킹 / 유닛 이코노믹스 / 획득 비용 (CAC) / 생애 가치 (LTV) / AARRR 퍼널 분석',                               '만원',                              '연합 활동',                                              'default', 18),
  ('learner', 15,   'Week 15', '데이터 기반 의사결정 (리텐션)',                                      '데이터 기반 의사결정 / 리텐션 차트 분석 / 이탈 지점 파악 / 코호트 분석 기법',                                        '만원',                              NULL,                                                     'default', 19),
  ('learner', 16,   'Week 16', '피봇팅(Pivoting)의 기술',                                          '피보팅 기술 / 가설 실패를 인정하는 법 / 핵심 가치만 남기고 깎아내기',                                                '만원',                              NULL,                                                     'default', 20),
  ('learner', NULL, 'EVENT',   'Demo Eve 밤샘',                                                   '중간 데모데이 전야제 / 피칭 리허설 / 외부 심사위원 피칭',                                                          '-',                                '중간 데모데이 & 서울대 창업동아리와 합동 데모데이',          'default', 21),
  ('learner', 17,   'Week 17', '유료 마케팅과 콘텐츠 전략',                                         '유로 마케팅 / 콘텐츠 전략 / Meta/Google 광고 기초 / 고효율 소재 제작 / AB 테스트',                                  '3만원',                             'Demo Eve 밤샘 (8/13)',                                   'default', 22),
  ('learner', 18,   'Week 18', '바이럴 루프와 커뮤니티 빌딩',                                       '바이럴 루프 / 커뮤니티 빌딩 / 유저가 유저를 불러오는 장치 설계 / 초기 팬덤 형성 전략',                                 '3만원',                             NULL,                                                     'default', 23),
  ('learner', 19,   'Week 19', '운영 자동화와 No-Code 확장',                                       '운영 자동화 / No-Code 확장 / 반복적인 CS / 운영 업무 자동화(Zapier, Make 활용)',                                    '3만원',                             NULL,                                                     'default', 24),
  ('learner', 20,   'Week 20', '중간 점검 : Death Valley 생존 보고',                                '지표가 안 나오는 이유 처절하게 분석하기 (Self-Roasting)',                                                          '3만원',                             '연합 활동',                                              'default', 25),
  ('learner', 21,   'Week 21', 'B2B 영업 및 제휴 전략',                                            '스케일링이란? / 병목 지점 찾기 / 자동화 심화',                                                                    '10만원',                            NULL,                                                     'default', 26),
  ('learner', 22,   'Week 22', '수익모델 구체화',                                                   '구독 서비스 vs 건당 결제 / 가격 심리학과 수익 극대화 / 수익모델 구체화',                                             '10만원',                            NULL,                                                     'default', 27),
  ('learner', 23,   'Week 23', '고객 경험(CX)과 브랜드 보이스',                                     '고객 경험(CX) / 브랜드 보이스',                                                                                  '10만원',                            '연합 활동',                                              'default', 28),
  ('learner', 24,   'Week 24', '법률 및 세무 기초',                                                '법인 설립 / 주주간 계약서 / 저작권 / 개인정보보호법',                                                              '10만원',                            NULL,                                                     'default', 29),
  ('learner', NULL, 'OFF',     '2학기 중간고사 OFF',                                              '시험 기간',                                                                                                   '-',                                NULL,                                                     'default', 30),
  ('learner', 25,   'Week 25', 'Product-Market Fit (PMF) 검증',                                   'Sean Ellis 테스트 / 재구매율, 재방문율 기반 PMF 판단',                                                            '30만원',                            '연합 활동',                                              'default', 31),
  ('learner', 26,   'Week 26', '조직 관리와 채용',                                                 '초기 팀 빌딩 전략 / 컬처 핏(Culture Fit) 정의 / 면접',                                                            '30만원',                            NULL,                                                     'default', 32),
  ('learner', 27,   'Week 27', '최종 데모데이 리허설',                                              '5분 피칭 / 3분 Q&A 대응 전략 / 시각 자료 시인성 개선',                                                            '30만원',                            'Final 해커톤 (11/7-8)',                                  'default', 33),
  ('learner', NULL, 'EVENT',   'Final 해커톤',                                                    '최종 데모데이 준비 (1박2일) / 피칭 리허설',                                                                       '-',                                'Final 해커톤',                                           'default', 34),
  ('learner', 28,   'Week 28', '최종 데모데이',                                                    '최종 리허설 / Q&A 마지막 준비 / 데모데이 당일 흐름',                                                               '100만원',                           '최종 데모데이 & 연고대 창업동아리와 합동 진행',              'default', 35),
  ('learner', 29,   'Week 29', '회고 + 네트워킹',                                                 'SPEC 4기 전체 회고 / 다음 단계 안내 / 알럼나이 네트워크',                                                          '100만원',                           NULL,                                                     'default', 36),
  ('learner', 30,   'Week 30', 'After SPEC',                                                     '스타트업 다음 단계 / 알럼나이 혜택 / 수료식',                                                                     '지속',                              '프로그램 종료',                                          'default', 37);

COMMIT;
