-- Default KPI templates for two-week startup team sprints.

create table if not exists public.team_kpi_templates (
  id uuid primary key default gen_random_uuid(),
  key text not null unique,
  title text not null,
  description text not null default '',
  category text not null default 'general',
  unit text not null default '',
  default_target_value numeric not null default 0,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists team_kpi_templates_touch_updated_at on public.team_kpi_templates;
create trigger team_kpi_templates_touch_updated_at
before update on public.team_kpi_templates
for each row execute function public.touch_updated_at();

alter table public.team_kpi_templates enable row level security;

drop policy if exists "team space members can read kpi templates" on public.team_kpi_templates;
create policy "team space members can read kpi templates"
on public.team_kpi_templates for select
using (
  exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('learner', 'preneur')
  )
  or public.is_team_space_admin()
);

drop policy if exists "team space admins manage kpi templates" on public.team_kpi_templates;
create policy "team space admins manage kpi templates"
on public.team_kpi_templates for all
using (public.is_team_space_admin())
with check (public.is_team_space_admin());

insert into public.team_kpi_templates (key, title, description, category, unit, default_target_value, sort_order)
values
  (
    'customer_interviews',
    'Customer Interviews',
    'Run direct customer interviews and capture validated pain points, quotes, and decision criteria.',
    'validation',
    'interviews',
    10,
    10
  ),
  (
    'problem_validation',
    'Problem Validation Score',
    'Count qualified target users who confirm the problem is urgent, frequent, and worth solving now.',
    'validation',
    'validated users',
    5,
    20
  ),
  (
    'waitlist_signups',
    'Waitlist Signups',
    'Collect qualified waitlist signups from target customers through landing page or outbound tests.',
    'growth',
    'signups',
    50,
    30
  ),
  (
    'mvp_tests',
    'MVP Tests Completed',
    'Run prototype, concierge, or MVP tests with real users and document learnings from each test.',
    'product',
    'tests',
    5,
    40
  ),
  (
    'active_users',
    'Active Users',
    'Track users who complete the core action in the product during the two-week sprint.',
    'product',
    'users',
    20,
    50
  ),
  (
    'revenue',
    'Revenue',
    'Measure paid revenue, deposits, or signed paid pilots generated by the team.',
    'business',
    'KRW',
    100000,
    60
  ),
  (
    'retention_followups',
    'Retention Follow-ups',
    'Measure users who return, ask for updates, or agree to a second session after the first interaction.',
    'retention',
    'follow-ups',
    5,
    70
  )
on conflict (key) do update
set
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  unit = excluded.unit,
  default_target_value = excluded.default_target_value,
  sort_order = excluded.sort_order,
  is_active = true,
  updated_at = now();
